import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });
import bars from "@/public/images/bars.svg";
import calendarIcon from "@/public/images/calendarIcon.svg";
import compose from "@/public/images/compose.svg";
import contactIcon from "@/public/images/contactIcon.svg";
import gamilIcon from "@/public/images/gamilIcon.svg";
import helpIcon from "@/public/images/helpIcon.svg";
import menuAppsIcon from "@/public/images/menuAppsIcon.svg";
import more from "@/public/images/more.svg";
import noteTakerIocn from "@/public/images/noteTakerIocn.svg";
import plus from "@/public/images/plus.svg";
import profilePic from "@/public/images/profilePic.svg";
import searchIcon from "@/public/images/searchIcon.svg";
import searchOption from "@/public/images/searchOption.svg";
import settingsIcon from "@/public/images/settingsIcon.svg";
import MenuComponent from "@/app/components/MenuComponent";
import LabelComponent from "@/app/components/LabelComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50 h-screen`}>
        <nav className="flex items-center pt-3 fixed w-full">
          <div className="w-1/6  px-5">
            <div className="flex items-center gap-3 ">
              <Image src={bars} alt="bars" />
              <Image src={gamilIcon} alt="gamilIcon" className="h-full"/>
              <div className="cursor-pointer text-2xl font-semibold text-gray-700">
                Gmail
              </div>
            </div>
          </div>
          <div className="w-5/6 px-4 ">
            <div className="flex justify-between items-center gap-6 mb-2">
              <div className="flex items-center bg-indigo-50 p-2  rounded-full w-full ">
                <div className="rounded-full cursor-pointer flex items-center justify-center hover:bg-gray-200 h-8 w-8">
                  <Image src={searchIcon} alt="searchIcon" />
                </div>

                <input
                  type="text"
                  placeholder="Search mail"
                  className="bg-transparent px-3 w-full outline-none pl-2"
                />
                <div className="rounded-full cursor-pointer flex items-center justify-center hover:bg-gray-200 h-8 w-8">
                  <Image src={searchOption} alt="searchOption" />
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-6 h-6 cursor-pointer">
                  <Image
                    src={helpIcon}
                    alt="helpIcon"
                  />
                </div>
                <div className="w-6 h-6  cursor-pointer">
                  <Image
                    src={settingsIcon}
                    alt="settingsIcon"
                  />
                </div>
                <div className="w-6 h-6 cursor-pointer">
                  <Image
                    src={menuAppsIcon}
                    alt="menuAppsIcon"
                  />
                </div>
                <div className="w-8 h-8 cursor-pointer">
                  <Image
                    src={profilePic}
                    alt="profilePic"
                  />
                </div>
              </div>
            </div>
          </div>
        </nav>
        <div className="h-screen pt-20 flex">
          {/* Left sidebar  */}

          <div className="w-1/6">
            <div className="flex flex-col ">
              <div className="px-4 mb-2">
                <button className="p-4 bg-[#C3E7FF] rounded-lg flex items-center gap-2">
                  <Image  src={compose} alt="compose" />
                  <div>Compose</div>
                </button>
              </div>
              <MenuComponent />
              <div className="flex items-center justify-between hover:bg-gray-200 rounded-r-full pl-4 pr-4 mr-2 py-2 cursor-pointer">
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4">
                    <Image  src={more} alt="more" />
                  </div>
                  <span className="text-gray-700 text-sm">More</span>
                </div>
                <div></div>
              </div>
              <div className="mt-6 ">
                <div className="text-lg font-semibold mb-4 text-gray-700 px-4 mr-2 flex justify-between items-center">
                  <h3>Labels</h3>
                  <button>
                    <Image  src={plus} alt="plus" />
                  </button>
                </div>
                <LabelComponent />
              </div>
            </div>
          </div>
          {/* <!-- Main Content --> */}
          <div className="w-5/6 px-4 h-full pb-4">
            <div className="bg-white rounded-lg h-full overflow-y-scroll">{children}</div>
          </div>
          {/* Right sidebar  */}
          <div className="pr-5 pt-4 flex flex-col items-center gap-6">
            <div className="w-4 h-4 cursor-pointer">
              <Image  src={calendarIcon} alt="calendarIcon" />
            </div>
            <div className="w-4 h-4 cursor-pointer">
              <Image  src={noteTakerIocn} alt="noteTakerIocn" />
            </div>
            <div className="w-4 h-4 cursor-pointer">
              <Image  src={contactIcon} alt="contactIcon" />
            </div>
            <hr className="border w-full" />
            <div className="w-4 h-4 cursor-pointer">
              <Image  src={plus} alt="plus" />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
